GET http://localhost:3000/users
###
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "diegohpezet@gmail.com",
  "password": "1234"
}
###
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "username": "dpezet",
  "email": "diegohpezet@gmail.com",
  "password": "1234"
}
###
GET http://localhost:3000/protected